apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
spec:
  minReadySeconds: 0
  template:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: movie-catalog-service
        image: "utsabroy/movie-catalog-service:e74f3ae"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3