k8-application:
  containers:
    movie-catalog-service:
      image:
        name: utsabroy/movie-catalog-service
        tag: e74f3ae
      ports:
        - 8080
      environment:
        PORT: 8080
      readinessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
  service:
    enabled: true
    type: NodePort
    ports:
      - port: 80
        targetPort: 8080
  ingress:
    enabled : true
    loadbalancers:
    - annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
      spec:
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: movie-catalog-service
                      port:
                        number: 80